# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: multipass 1.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "multipass".freeze
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["rick".freeze]
  s.date = "2017-04-28"
  s.email = "technoweenie@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION.yml",
    "lib/multipass.rb",
    "multipass.gemspec",
    "test/multipass_test.rb"
  ]
  s.homepage = "https://github.com/entp/multipass".freeze
  s.rubygems_version = "1.8.23".freeze
  s.summary = "Bare bones implementation of encoding and decoding MultiPass values for SSO.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ezcrypto>.freeze, [">= 0"])
    else
      s.add_dependency(%q<ezcrypto>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<ezcrypto>.freeze, [">= 0"])
  end
end

