# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "multipass"
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rick"]
  s.date = "2012-08-09"
  s.email = "technoweenie@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION.yml",
    "lib/multipass.rb",
    "multipass.gemspec",
    "test/multipass_test.rb"
  ]
  s.homepage = "https://github.com/entp/multipass"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Bare bones implementation of encoding and decoding MultiPass values for SSO."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ezcrypto>, [">= 0"])
    else
      s.add_dependency(%q<ezcrypto>, [">= 0"])
    end
  else
    s.add_dependency(%q<ezcrypto>, [">= 0"])
  end
end

